"""California FAQ page, About, Privacy, Terms."""
FAQ_PAGE = [
    ("How much does it cost to work with ECOS Medicare Solutions?", "Nothing. Independent Medicare agents are paid by the insurance carriers when you enroll, so comparing plans, answering questions and reviewing your coverage each year is free to you. Your premium is the same whether you enroll through us, another agent or the carrier directly."),
    ("What is California&rsquo;s Medigap birthday rule?", "Each year, for 60 days beginning on your birthday, anyone who already holds a Medigap policy can switch to any insurer&rsquo;s plan with the same or lesser benefits, with no medical underwriting and no new waiting period. It is why Californians should re-shop their supplement every year, and we do it for our clients before every birthday."),
    ("Can I keep Kaiser when I go on Medicare?", "Yes, through Kaiser Permanente Senior Advantage, a Medicare Advantage plan. You cannot keep Kaiser doctors with Original Medicare and a Medigap policy, because Kaiser does not generally treat Original Medicare patients outside emergencies. Our Kaiser page compares the two paths honestly."),
    ("My Medicare Advantage PPO was discontinued in my California county. What now?", "You get a Special Enrollment Period to choose a new plan and, because you lost coverage through no fault of your own, generally a guaranteed-issue right to buy a Medigap policy without health questions, usually within 63 days of the coverage ending. Anthem&rsquo;s PPO exit and Aetna&rsquo;s county cuts for 2026 both qualify. Call before the deadline on your notice."),
    ("What does &lsquo;medical group&rsquo; mean on my Advantage plan?", "Most non-Kaiser Advantage plans in California delegate your care to a physician group tied to your primary doctor. That group approves referrals and decides which specialists and hospitals you can use. Two people on the same plan can have different access; checking the group is as important as checking the plan."),
    ("I am under 65 on Medicare because of a disability. Can I buy Medigap in California?", "Yes. California requires insurers to offer Medigap to people under 65 on Medicare because of disability, with a six-month open enrollment when Part B begins. Premiums for under-65 policies are higher, and the requirement does not extend to people under 65 with ESRD. You get a fresh open enrollment for every plan at 65."),
    ("Does Stanford, UCLA or Cedars-Sinai accept Medicare Advantage plans?", "All three accept Original Medicare and therefore every Medigap policy. Each contracts with some Medicare Advantage plans and medical groups and not others, and the lists change yearly. If one of them, or City of Hope or UCSF, is your care, we confirm the plan&rsquo;s and the group&rsquo;s status in writing before you enroll."),
    ("I am retiring through CalPERS. Does this apply to me?", "Partly. CalPERS requires you to enroll in Medicare Parts A and B when eligible and move into a CalPERS Medicare plan to keep CalPERS coverage; many State and CSU retirees get Part B reimbursed. Those plans are separate from the individual-market plans we sell, but we can still explain Medicare, Part B timing and IRMAA plainly."),
    ("I am moving to Arizona, Nevada or Texas. Does my plan come with me?", "Original Medicare and a Medigap policy do, re-rated for the new state; an Advantage or Part D plan does not, and the move opens a Special Enrollment Period. California&rsquo;s birthday rule does not travel. Our sister agencies in Arizona, Nevada, Texas, Utah, Colorado and Florida can take it from there."),
    ("A wildfire made me miss an enrollment deadline. Am I out of luck?", "Usually not. A FEMA-declared disaster opens a Special Enrollment Period for people who lived in a declared county, or who rely on someone who did, and missed a valid election period because of it. Part D plans must also allow early refills in the emergency area. Our Wildfires page has the details."),
    ("I have TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable Part D coverage. You do need Part B, and you must keep it. Our Veterans page covers the exceptions."),
    ("I use the VA. Do I still need Medicare Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying Part B adds a lifelong penalty, and VA care does not cover you at non-VA hospitals in an emergency. Most California veterans keep both."),
    ("When can I enroll in or change my Medicare plan in California?", "Your Initial Enrollment Period is the seven months around your 65th birthday. The Annual Election Period is October 15 to December 7, and Medicare Advantage Open Enrollment runs January 1 to March 31. Moving, losing a plan, a disaster declaration, or qualifying for Medi-Cal or Extra Help each open a Special Enrollment Period, and the birthday rule covers Medigap switches every year."),
    ("What are the [[YEAR]] Medicare costs?", "Part B premium $202.90 a month, Part B deductible $283, Part A hospital deductible $1,736 per benefit period, Part D out-of-pocket cap $2,100, maximum Part D deductible $615. IRMAA surcharges begin at $109,000 of modified adjusted gross income for a single filer and $218,000 for a joint return, looking back two tax years. See our costs page for the full table."),
    ("Can Medi-Cal help pay my Part B premium?", "Possibly. California&rsquo;s Medicare Savings Programs (QMB, SLMB and QI) pay the Part B premium for people with limited income and resources, and QMB also covers Medicare&rsquo;s deductibles and copays. Apply through your county Medi-Cal office or BenefitsCal; HICAP (1-800-434-0222) can help. An asset limit of $130,000 for one person returned on January 1, 2026."),
    ("What is a Medi-Medi Plan?", "An exclusively aligned Dual Special Needs Plan: a Medicare Advantage plan run by the same organization as your Medi-Cal managed-care plan, so both programs are coordinated by one care team. Available in 41 counties for 2026 under CalAIM."),
    ("Where can I get free, unbiased Medicare counseling in California?", "HICAP, the Health Insurance Counseling and Advocacy Program, California&rsquo;s State Health Insurance Assistance Program, run by the Department of Aging through local Area Agencies on Aging: 1-800-434-0222. It is free and independent, and we point people to it."),
    ("Do you offer every plan available in my area?", "No. We represent a number of insurance organizations and products in California, not all of them. For a complete list, use Medicare.gov, 1-800-MEDICARE or HICAP."),
    ("Where can I verify your California license?", "Darin Weidauer holds California insurance license #0M00978 (NPN 18580338). You can verify it through the California Department of Insurance license lookup at insurance.ca.gov, or through the NIPR."),
    ("Do you meet in person?", "We work with Californians statewide by phone and video, which is how most people prefer it across a state this size. If you are in Arizona for part of the year, our sister agency has offices in Mesa and Sun City."),
]

ABOUT_BODY = """<div class="author" style="margin-bottom:2rem">
<img class="author__photo" src="/darin.jpg" width="600" height="600" alt="Darin Weidauer, independent Medicare insurance agent and credentialed gerontologist" loading="lazy" decoding="async">
<div>
<ul class="creds"><li>CA License #0M00978 · NPN 18580338</li><li>Credentialed gerontologist (2014)</li><li>Registered Social Security Analyst&reg;</li><li>MBA, Pepperdine</li><li>Master&rsquo;s in Long-Term Care, USC</li><li>22-yr USAF veteran (retired officer)</li></ul>
<p>Darin Weidauer (CA License #0M00978) is an independent Medicare insurance agent, credentialed gerontologist, and Registered Social Security Analyst&reg; who helps California retirees and people approaching 65 make sense of their Medicare options &mdash; clearly, patiently, and with no cost to them.</p>
</div></div>
<h2>Background</h2>
<p>A 22-year U.S. Air Force veteran who retired as an officer, Darin holds five master&rsquo;s degrees, including an MBA and a Master&rsquo;s in Dispute Resolution from Pepperdine University and a Master&rsquo;s in Long-Term Care from the University of Southern California&rsquo;s Leonard Davis School of Gerontology, where he became a credentialed gerontologist in 2014 &mdash; studying the human side of aging, not just the paperwork. Both degrees are Californian; so is a good part of his career.</p>
<p>A former Professor of Aerospace Studies at Loyola Marymount University in Los Angeles who has lectured at more than 50 colleges and universities, Darin now channels that teaching instinct into plain-English Medicare education: one-on-one reviews, no-cost community workshops, the free 295-page guide <a href="/retirement-guide"><em>Retire With Confidence</em></a>, and the pages on this site, every one of which he wrote or reviewed. He is also the founder of MyECOS360, an agency operating system for independent insurance agents, and the author of its training on <a href="https://www.myecos360.com/insurance-lead-economics">insurance lead economics</a>.</p>
<h2>How he is paid, and what that means for you</h2>
<p>ECOS Medicare Solutions is an independent agency: appointed with a number of Medicare Advantage, Medigap and Part D carriers in California, employed by none of them. When you enroll in a plan through us, the carrier pays us a commission. That commission comes out of the carrier&rsquo;s filed rate &mdash; it is never added to your premium. You pay the same whether you enroll through us, through another agent, or directly with the insurer; going direct does not make a policy cheaper, and using us does not make it dearer.</p>
<p>We do not represent every plan sold in California, and we say so on every page. For a complete list, use Medicare.gov, 1-800-MEDICARE, or HICAP (1-800-434-0222), California&rsquo;s free and independent counseling program.</p>
<h2>Licensing</h2>
<p>Darin Weidauer holds <strong>California insurance license #0M00978</strong> and is a licensed insurance agent in California and sixteen other states &mdash; Arizona, Colorado, Florida, Georgia, Hawaii, Indiana, Minnesota, Nevada, New Mexico, North Carolina, Ohio, South Carolina, Tennessee, Texas, Utah and Washington &mdash; under National Producer Number 18580338. You can verify the California license through the <a href="https://www.insurance.ca.gov" rel="noopener">California Department of Insurance</a> license lookup, or any state&rsquo;s through the NIPR. California law requires the license number to appear next to a licensee&rsquo;s name in advertising, which is why you will see it throughout this site. The multi-state licence is what lets us follow Californians to <a href="/moving">Arizona, Nevada, Texas and Utah</a> when they retire out of state.</p>
<h2>Where else you will find him</h2>
<ul>
<li><a href="https://www.myecos360.com/darin-weidauer" rel="noopener">Author page at MyECOS360</a> &mdash; the canonical profile</li>
<li><a href="https://www.linkedin.com/in/darin-weidauer-3165a816b/" rel="noopener">LinkedIn</a> and <a href="https://www.youtube.com/channel/UCD1XkkknhQ3UT-8AteYD3vQ" rel="noopener">YouTube</a></li>
<li>Sister sites: <a href="https://www.medicareenrollmentarizona.com" rel="noopener">Medicare Enrollment Arizona</a>, <a href="https://medicareenrollmentnevada.com" rel="noopener">Medicare Enrollment Nevada</a>, <a href="https://texasmedicareenrollment.com" rel="noopener">Texas Medicare Enrollment</a>, <a href="https://medicareenrollmentutah.com" rel="noopener">Medicare Enrollment Utah</a>, <a href="https://medicareenrollmentflorida.com" rel="noopener">Medicare Enrollment Florida</a>, <a href="https://minnesotamedicareenrollment.com" rel="noopener">Minnesota Medicare Enrollment</a>, and <a href="https://www.mymedigaprate.com" rel="noopener">MyMedigapRate</a>, where Medigap rate filings &mdash; California&rsquo;s included &mdash; are published filing by filing.</li>
</ul>
<h2>How to reach him</h2>
<p>Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form at the top of this page. We work with Californians statewide by phone and video.</p>
"""

PRIVACY_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 4, 2026. This policy is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>This Privacy Policy explains how ECOS Medicare Solutions ("we," "us") handles information collected through Californiamedicareenrollment.com (the "Site").</p>
<h2>Information we collect</h2>
<p>When you submit a form on the Site, we collect the information you provide: your name, phone number, email address, ZIP code or city, the topic you select, and a record of the consent you give (including the consent language shown and a date/time stamp). We do not ask for, and ask you not to send, health information through the form.</p>
<h2>How we use it</h2>
<p>We use your information to contact you about Medicare plan options and to provide the help you requested &mdash; by phone call, text message and email, consistent with the consent you provide. A licensed insurance agent may contact you. We do not sell or share your personal information for cross-context behavioral advertising.</p>
<h2>How your form is processed</h2>
<p>Our forms are delivered through a third-party form-processing service (Web3Forms), which transmits your submission to us. The Site loads web fonts from Google Fonts. We aim to limit data sharing to what is needed to operate the Site and respond to you.</p>
<h2>Analytics</h2>
<p>When enabled, we use Google Analytics to understand how visitors find and use this Site &mdash; which pages are read, and whether people call or submit a form. Google Analytics sets cookies and receives your IP address, device and browser type, and the pages you view. We use it in aggregate to improve the Site.</p><p>We do not send Google Analytics your name, phone number, email address or any information you type into a form. You can opt out across all sites using Google&rsquo;s <a href="https://tools.google.com/dlpage/gaoptout" rel="nofollow noopener" target="_blank">browser opt-out add-on</a>, or by using your browser&rsquo;s cookie controls.</p>
<h2>Your California privacy rights</h2>
<p>California residents have rights under the California Consumer Privacy Act, as amended by the California Privacy Rights Act, including the right to know what personal information we collect, the right to delete it, the right to correct it, and the right to opt out of its sale or sharing. We do not sell personal information. To exercise any of these rights, contact us using the details below; we will verify your request and respond within the time the law allows, and we will not discriminate against you for exercising them. You may designate an authorized agent to make a request on your behalf.</p>
<h2>Your choices</h2>
<p>You can opt out of further contact at any time by telling us, replying STOP to texts, or unsubscribing from emails. To request that we delete your information, contact us using the details below.</p>
<h2>Data security</h2>
<p>We take reasonable measures to protect the information you share, but no method of transmission over the internet is completely secure.</p>
<h2>Children</h2>
<p>The Site is intended for adults making Medicare decisions and is not directed to children under 13.</p>
<h2>Contact us</h2>
<p>Questions about this policy? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance. Darin Weidauer, CA License #0M00978.</p>
"""

TERMS_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 4, 2026. This document is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>By using Californiamedicareenrollment.com (the "Site"), operated by ECOS Medicare Solutions, you agree to these Terms of Use.</p>
<h2>Informational purpose</h2>
<p>The Site provides general information about Medicare to help you make decisions. It is not legal, tax or medical advice, and it is not a substitute for the official Medicare program or for California&rsquo;s free counseling program, HICAP. Medicare plan availability, costs and rules change and vary by county.</p>
<h2>Insurance offered through a licensed agent</h2>
<p>Insurance products referenced on the Site are offered through a licensed insurance agent (Darin Weidauer, California insurance license #0M00978, NPN 18580338). Enrollment is subject to plan terms and eligibility. We do not offer every plan available in your area.</p>
<h2>No guarantee of accuracy</h2>
<p>We work to keep figures current and cite the year and source, but we do not warrant that all information is complete, current or error-free. Always confirm details with the official sources noted on the Site.</p>
<h2>External links</h2>
<p>The Site links to third-party websites (such as Medicare.gov, dhcs.ca.gov and aging.ca.gov) and to other sites operated by ECOS Medicare Solutions. We are not responsible for the content or practices of third-party sites.</p>
<h2>Limitation of liability</h2>
<p>To the fullest extent permitted by law, ECOS Medicare Solutions is not liable for any damages arising from your use of the Site.</p>
<h2>Governing law</h2>
<p>These Terms are governed by the laws of the State of California.</p>
<h2>Contact us</h2>
<p>Questions? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a> or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance.</p>
"""
