"""California regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
EXIT = ("For the 2026 plan year Anthem Blue Cross ended its Medicare Advantage PPO plans in California, Aetna closed plans and left counties, and UnitedHealthcare and Humana withdrew from counties too. "
        "A plan leaving you gives you a Special Enrollment Period and, in most cases, a guaranteed-issue right to a Medigap policy without health questions.")
NET = "Each system contracts with some Medicare Advantage plans and not others, and the lists change every October. With Original Medicare and a Medigap policy there is no network to check, except Kaiser, which is reached only through Kaiser Senior Advantage. We confirm your doctors before you enroll."
KAISER = "Kaiser Permanente is a closed system: you keep Kaiser doctors on Medicare through Kaiser Senior Advantage, not through Original Medicare and a Medigap policy. If you are leaving Kaiser, or joining it, that is the first decision, and we walk through it plainly."

REGIONS = [
    dict(slug="los-angeles-county", name="Los Angeles County", short="Los Angeles County", scene="losangeles",
         eyebrow="Medicare by region · Los Angeles County",
         h1="Medicare help across Los Angeles County",
         sub="Ten million people, the largest Medicare market in America, Kaiser on one side and UCLA, Cedars-Sinai, Keck, Providence and City of Hope on the other &mdash; and the county where the 2026 PPO shake-up hit hardest.",
         counties="Los Angeles",
         cities=["los-angeles", "long-beach", "pasadena", "santa-clarita", "torrance"],
         systems=["Kaiser Permanente (Senior Advantage only)", "UCLA Health", "Cedars-Sinai", "Keck Medicine of USC", "Providence (Southern California)", "City of Hope", "Dignity Health / CommonSpirit", "MemorialCare", "VA Greater Los Angeles &amp; VA Long Beach"],
         note="<p><strong>What changed for 2026:</strong> Anthem Blue Cross ended its Advantage PPO plans in California and Aetna closed plans across the county, which pushed a lot of Angelenos who chose a PPO for its out-of-network freedom into a decision between an HMO, a different PPO and a Medigap policy. The county menu is still the deepest in the country &mdash; Kaiser, SCAN, Alignment, Blue Shield, UnitedHealthcare, Humana, Wellcare, Central Health, Brand New Day and many more &mdash; and every plan rides on a different set of medical groups.</p>",
         intro=["Los Angeles County is Medicare at its most crowded: dozens of Advantage plans, hundreds of medical groups, and a care map where the plan you pick decides whether you see a UCLA cardiologist or a Cedars one. Advantage plans here work through delegated medical groups (Optum, Regal, HealthCare Partners, Facey, Torrance Memorial IPA and others), so the question is not only which hospital but which group your primary doctor belongs to.",
                "Kaiser is its own answer: roughly a third of the county&rsquo;s seniors take Medicare through Senior Advantage and never touch the rest of the menu. For everyone else, a Medigap policy with Original Medicare opens every non-Kaiser door in the county at once, and California&rsquo;s birthday rule lets you re-shop it every year."],
         faqs=[("Which Medicare plans are available in Los Angeles County?", "The deepest Medicare Advantage menu in the country, including many Dual Special Needs Plans and Medi-Medi Plans, plus every Medigap carrier in California and the full Part D lineup. Availability is set by county and changes each plan year; for 2026 Anthem&rsquo;s PPOs left and Aetna reduced its plans here."),
               ("Does UCLA or Cedars-Sinai take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="orange-county", name="Orange County", short="Orange County", scene="coast",
         eyebrow="Medicare by region · Anaheim, Irvine, Huntington Beach &amp; South County",
         h1="Medicare help across Orange County",
         sub="Hoag, UCI Health, Providence St. Joseph and Mission, MemorialCare and Kaiser &mdash; a county where medical-group affiliation decides more than the plan name does, and one of the largest retiree populations in the state.",
         counties="Orange",
         cities=["anaheim", "irvine", "huntington-beach", "mission-viejo"],
         systems=["Hoag", "UCI Health", "Providence St. Joseph &amp; St. Jude", "Providence Mission Hospital", "MemorialCare (Orange Coast, Saddleback)", "Kaiser Permanente (Senior Advantage only)", "CalOptima (Medi-Cal / OneCare)"],
         note="<p><strong>What to watch:</strong> Orange County&rsquo;s Advantage plans are built on medical groups &mdash; Hoag Physician Partners, Optum, Monarch, Greater Newport, MemorialCare Medical Group &mdash; and the same plan name can mean a different set of doctors from one group to the next. For 2026 Anthem&rsquo;s PPOs left and Aetna reduced plans here. Dual-eligible residents have CalOptima OneCare, the county&rsquo;s Medi-Medi Plan.</p>",
         intro=["Orange County has one of the most competitive Medicare Advantage markets in the state, with SCAN, Alignment, Blue Shield, UnitedHealthcare, Humana, Wellcare and Kaiser all present and $0-premium plans everywhere. The trade-off is the medical group: pick the plan, then the group, then find out whether your Hoag or UCI specialist is in it.",
                "South County retirees in Laguna Woods, Mission Viejo and San Clemente tend to ask about Providence Mission and Saddleback first; north-county residents about UCI, St. Jude and St. Joseph. A Medigap policy sidesteps all of it, at a premium the birthday rule lets you re-shop each year."],
         faqs=[("Which Medicare plans are available in Orange County?", "A deep Medicare Advantage menu, CalOptima OneCare for people with both Medicare and Medi-Cal, every Medigap carrier in California and the full Part D lineup. Availability changes each plan year."),
               ("Does Hoag or UCI Health take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="san-diego-county", name="San Diego County", short="San Diego County", scene="harbor",
         eyebrow="Medicare by region · San Diego, North County &amp; the South Bay",
         h1="Medicare help across San Diego County",
         sub="Scripps, Sharp, UC San Diego Health and Kaiser, the largest Navy and Marine retiree community in the country, and a border county with its own Medicare habits.",
         counties="San Diego",
         cities=["san-diego", "chula-vista", "oceanside", "escondido", "san-diego-navy"],
         systems=["Scripps Health", "Sharp HealthCare", "UC San Diego Health", "Kaiser Permanente (Senior Advantage only)", "Palomar Health", "Tri-City Medical Center", "Naval Medical Center San Diego (TRICARE)", "VA San Diego (La Jolla)"],
         note="<p><strong>What to watch:</strong> San Diego&rsquo;s Advantage market splits along system lines &mdash; plans built on Sharp and its medical groups, plans built on Scripps, plans that include UC San Diego, and Kaiser &mdash; and Scripps in particular has been selective about which Advantage contracts it keeps. TRICARE For Life covers a huge share of the county&rsquo;s retirees, which changes the whole calculation.</p>",
         intro=["San Diego County has a mature Medicare Advantage market where the first question is which hospital system you want to be inside: Sharp, Scripps, UC San Diego or Kaiser. Each contracts on its own terms, Scripps has trimmed Advantage relationships in recent years, and the plan brochure rarely makes the split obvious.",
                "The county&rsquo;s military population is the largest in the nation, and for a TRICARE For Life household the answer is usually Original Medicare plus TFL with nothing else needed. North County, Escondido and the South Bay each have their own hospital anchors, and Medi-Medi Plans serve the county&rsquo;s dual-eligible residents."],
         faqs=[("Which Medicare plans are available in San Diego?", "A deep Medicare Advantage menu, Medi-Medi Plans for people with both Medicare and Medi-Cal, every Medigap carrier in California and the full Part D lineup. Availability changes each plan year."),
               ("Does Scripps or Sharp take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="inland-empire", name="Inland Empire &amp; the Desert", short="the Inland Empire", scene="desert",
         eyebrow="Medicare by region · Riverside, San Bernardino, Temecula &amp; the Coachella Valley",
         h1="Medicare help across the Inland Empire and the Coachella Valley",
         sub="Loma Linda, Riverside&rsquo;s hospitals, Kaiser Fontana and Riverside, Eisenhower and Desert Regional in the desert &mdash; the fastest-growing retiree region in the state, and one of the thinnest in specialists per capita.",
         counties="Riverside, San Bernardino",
         cities=["riverside", "san-bernardino", "temecula", "palm-springs", "victorville"],
         systems=["Loma Linda University Health", "Riverside University Health System", "Riverside Community Hospital (HCA)", "Kaiser Permanente Fontana &amp; Riverside (Senior Advantage only)", "Eisenhower Health (Rancho Mirage)", "Desert Regional (Palm Springs)", "Temecula Valley Hospital", "VA Loma Linda"],
         note="<p><strong>What to watch:</strong> the Inland Empire has a deep Advantage menu in Riverside and San Bernardino proper and a thinner one in the high desert and the mountains, where UnitedHealthcare and Humana&rsquo;s 2026 county exits landed. The Coachella Valley is its own market: Eisenhower Health anchors it and contracts selectively, and a large share of residents split the year with somewhere cooler, which is where a Medigap policy&rsquo;s any-provider access earns its keep. Inland Empire Health Plan runs the region&rsquo;s Medi-Medi Plan.</p>",
         intro=["Two of the largest counties in the country by area, with a Medicare map that runs from Kaiser Fontana and Loma Linda in the west to the Coachella Valley, the high desert and mountain communities where a single hospital serves a huge territory. Advantage plans work through medical groups here too, and specialist access is the thing to check before premium.",
                "Temecula and Murrieta are booming with retirees from Orange County and San Diego; Palm Springs and the desert cities hold one of the largest seasonal populations in the West. Both ask the same question in different words: will my plan travel?"],
         faqs=[("Which Medicare plans are available in Riverside and San Bernardino counties?", "A deep Advantage menu in the cities, thinner in the high desert and mountains; IEHP DualChoice for people with both Medicare and Medi-Cal; every Medigap carrier in California and the full Part D lineup."),
               ("Does Loma Linda or Eisenhower take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="bay-area", name="The San Francisco Bay Area", short="the Bay Area", scene="goldengate",
         eyebrow="Medicare by region · San Francisco, Oakland, San Jose, the Peninsula &amp; the North Bay",
         h1="Medicare help across the Bay Area",
         sub="UCSF, Stanford, Sutter, John Muir and Kaiser&rsquo;s home turf &mdash; nine counties, the highest Medigap premiums in the state, and the biggest Kaiser share anywhere.",
         counties="San Francisco, Alameda, Contra Costa, Santa Clara, San Mateo, Marin, Sonoma, Napa, Solano",
         cities=["san-francisco", "oakland", "san-jose", "walnut-creek", "santa-rosa", "travis-afb"],
         systems=["Kaiser Permanente (Senior Advantage only)", "UCSF Health", "Stanford Health Care", "Sutter Health (CPMC, Alta Bates Summit, PAMF)", "John Muir Health", "El Camino Health", "Santa Clara Valley Medical Center", "VA Palo Alto &amp; VA San Francisco"],
         note="<p><strong>What to watch:</strong> the Bay Area is Kaiser country &mdash; in several counties Senior Advantage is the single largest Medicare plan by a wide margin. Outside Kaiser, the Advantage menu is thinner than Southern California&rsquo;s and built on Sutter, John Muir, Stanford and UCSF contracts that change yearly; Anthem&rsquo;s 2026 PPO exit removed one of the few broad-network options. Medigap premiums here run among the highest in the state, which makes the annual birthday-rule re-shop worth real money.</p>",
         intro=["The Bay Area Medicare decision usually starts with Kaiser: stay in, or come out. Staying in means Senior Advantage; coming out means Original Medicare with a Medigap policy for UCSF, Stanford and Sutter without a network, or a non-Kaiser Advantage plan built on one of those systems. Stanford and UCSF both contract selectively with Advantage plans.",
                "The North Bay (Marin, Sonoma, Napa) and Solano have shorter menus and their own anchors: MarinHealth, Sutter Santa Rosa and Providence Santa Rosa Memorial, Queen of the Valley, and NorthBay and Kaiser in Solano, where Travis Air Force Base adds a large TRICARE For Life community."],
         faqs=[("Which Medicare plans are available in the Bay Area?", "Kaiser Senior Advantage plus a moderate non-Kaiser Advantage menu that varies by county, Medi-Medi Plans in the larger counties, every Medigap carrier in California and the full Part D lineup. Availability changes each plan year."),
               ("Does Stanford or UCSF take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="sacramento-valley", name="Sacramento &amp; the Northern Valley", short="the Sacramento region", scene="vineyards",
         eyebrow="Medicare by region · Sacramento, Roseville, Elk Grove, Folsom &amp; the foothills",
         h1="Medicare help across the Sacramento region",
         sub="UC Davis Health, Sutter, Dignity Mercy and Kaiser, the largest CalPERS retiree population in the state, and foothill counties where menus thin out fast.",
         counties="Sacramento, Placer, El Dorado, Yolo, Sutter, Yuba, Nevada",
         cities=["sacramento", "roseville", "elk-grove", "folsom"],
         systems=["UC Davis Health", "Sutter Health (Sacramento, Roseville, Davis)", "Dignity Health Mercy", "Kaiser Permanente Sacramento &amp; Roseville (Senior Advantage only)", "Adventist Health &amp; Rideout (Marysville)", "VA Northern California (Mather)"],
         note="<p><strong>What to watch:</strong> a large share of the region&rsquo;s retirees are CalPERS members, whose Medicare plans come through CalPERS rather than the individual market &mdash; a different menu with its own rules. For everyone else, the Advantage market is split between Kaiser, plans built on Sutter and Dignity, and plans that include UC Davis; foothill and mountain counties saw UnitedHealthcare and Humana exits for 2026.</p>",
         intro=["Sacramento is a four-system town &mdash; UC Davis, Sutter, Dignity and Kaiser &mdash; and every Advantage plan draws a line through it. UC Davis is the region&rsquo;s academic and cancer center and contracts selectively; Sutter and Dignity anchor most of the non-Kaiser plans; Kaiser runs its own world from Sacramento, South Sacramento and Roseville.",
                "Roseville, Rocklin, Lincoln and Folsom are among the fastest-growing retirement addresses in Northern California. Up the hill in El Dorado, Nevada and Placer counties, menus shorten and a Medigap policy&rsquo;s no-network access becomes the practical choice."],
         faqs=[("Which Medicare plans are available in Sacramento?", "A moderate-to-deep Medicare Advantage menu in Sacramento and Placer counties, thinner in the foothills; every Medigap carrier in California and the full Part D lineup. CalPERS retirees choose from CalPERS&rsquo;s own Medicare plans."),
               ("Does UC Davis Health take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="central-valley", name="The Central Valley", short="the Central Valley", scene="valley",
         eyebrow="Medicare by region · Fresno, Bakersfield, Modesto, Stockton &amp; Visalia",
         h1="Medicare help across the Central Valley",
         sub="Community Health System, Saint Agnes, Adventist, Dignity, Kaiser and Kern Medical &mdash; the counties with the highest share of dual-eligible residents in the state and some of the strongest Medi-Medi Plan growth.",
         counties="Fresno, Kern, Stanislaus, San Joaquin, Tulare, Merced, Madera, Kings",
         cities=["fresno", "bakersfield", "modesto", "stockton", "visalia", "lemoore-nas"],
         systems=["Community Health System (Fresno)", "Saint Agnes Medical Center", "Kaiser Permanente Fresno, Modesto &amp; Manteca (Senior Advantage only)", "Adventist Health (Bakersfield, Hanford, Lodi)", "Dignity Health (Bakersfield, Stockton)", "Kern Medical", "Sutter &amp; Doctors Medical Center (Modesto)", "VA Central California (Fresno)"],
         note="<p><strong>What to watch:</strong> the Valley has deep Advantage menus in Fresno, Kern, Stanislaus and San Joaquin, a large dual-eligible population served by Medi-Medi Plans (expanded for 2026 under CalAIM), and long drives to specialists in Tulare, Kings and Madera counties. Specialist access, not premium, is usually the deciding factor. The Medi-Cal asset limit returning in 2026 affects more households here than anywhere.</p>",
         intro=["The Central Valley&rsquo;s Medicare market is big, price-competitive and split by county: Fresno&rsquo;s plans build on Community Health System and Saint Agnes, Bakersfield&rsquo;s on Adventist, Dignity and Kern Medical, Modesto and Stockton&rsquo;s on Sutter, Tenet and Dignity, with Kaiser present in Fresno and the north valley. A $0-premium plan is easy to find; one that includes your cardiologist and a Fresno or Stanford referral path takes checking.",
                "More of the Valley&rsquo;s Medicare population qualifies for Medi-Cal and the Medicare Savings Programs than in any other region, so our first question here is often whether a program pays your Part B premium before we compare plans at all."],
         faqs=[("Which Medicare plans are available in Fresno and Bakersfield?", "Deep Medicare Advantage menus in both, Medi-Medi Plans for people with both Medicare and Medi-Cal, every Medigap carrier in California and the full Part D lineup. Rural Valley counties have shorter menus."),
               ("Does Community Regional or Adventist take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="central-coast", name="The Central Coast", short="the Central Coast", scene="coast",
         eyebrow="Medicare by region · Santa Barbara, Ventura, San Luis Obispo &amp; Monterey",
         h1="Medicare help across the Central Coast",
         sub="Cottage, Sansum, Community Memorial, Dignity, Tenet, Montage and Salinas Valley Health &mdash; retirement country with short Advantage menus, high Medigap prices, and a real reason to shop the birthday rule.",
         counties="Santa Barbara, Ventura, San Luis Obispo, Monterey, Santa Cruz",
         cities=["santa-barbara", "ventura", "san-luis-obispo", "monterey", "vandenberg-sfb"],
         systems=["Cottage Health (Santa Barbara)", "Sansum Clinic (Sutter)", "Community Memorial Health System (Ventura)", "Dignity Health (St. John&rsquo;s, Marian, French)", "Tenet (Sierra Vista, Twin Cities)", "Montage Health (Monterey)", "Salinas Valley Health", "Kaiser Permanente (Ventura County clinics; Senior Advantage only)"],
         note="<p><strong>What to watch:</strong> the Central Coast has fewer Advantage plans than Los Angeles or the Bay Area and fewer medical groups, so a plan that looks broad statewide can be narrow here. Several counties have one dominant system &mdash; Cottage in Santa Barbara, Montage on the Monterey Peninsula, Tenet and Dignity in San Luis Obispo &mdash; and Original Medicare with a Medigap policy is a common choice for exactly that reason.</p>",
         intro=["Between Ventura and Santa Cruz the Medicare map is a string of one- and two-system towns. Santa Barbara runs on Cottage and Sansum; Ventura County on Community Memorial, Dignity St. John&rsquo;s and the county system, with Kaiser clinics but no Kaiser hospital; San Luis Obispo on Tenet and Dignity; the Monterey Peninsula on Montage and Salinas on Salinas Valley Health. Advantage menus are moderate and the medical groups small.",
                "Retirees here travel &mdash; to Stanford, UCLA and Cedars for specialty care, and to children elsewhere &mdash; which is why Medigap&rsquo;s any-provider access is worth its premium for many, and why California&rsquo;s birthday rule matters: it lets you move to a cheaper carrier every year without underwriting."],
         faqs=[("Which Medicare plans are available on the Central Coast?", "A moderate Medicare Advantage menu that varies county by county, every Medigap carrier in California and the full Part D lineup. Availability changes each plan year."),
               ("Does Cottage or Montage take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="north-state", name="The North State", short="the North State", scene="redwoods",
         eyebrow="Medicare by region · Redding, Chico, Eureka &amp; the far north",
         h1="Medicare help across the North State",
         sub="Mercy Redding, Shasta Regional, Enloe, Providence St. Joseph Eureka and long drives between them &mdash; the counties where Advantage plans left for 2026, and where a Medigap policy is often the practical answer.",
         counties="Shasta, Butte, Humboldt, Tehama, Siskiyou, Mendocino, Lake, Del Norte, Trinity, Lassen, Plumas, Modoc, Glenn, Colusa",
         cities=["redding", "chico", "eureka"],
         systems=["Mercy Medical Center Redding (Dignity)", "Shasta Regional Medical Center", "Enloe Health (Chico)", "Providence St. Joseph (Eureka)", "Adventist Health (Ukiah, Clearlake)", "Sutter (Yuba City, Lakeside)", "UC Davis Health (referrals)"],
         note="<p><strong>What changed for 2026:</strong> the North State is where the national Advantage pullback landed hardest in California &mdash; UnitedHealthcare, Humana and Aetna withdrew from rural counties, and some counties (Plumas, Modoc, Trinity among them) have only one or two plans or none. A plan leaving you opens a Special Enrollment Period and, in most cases, a guaranteed-issue right to Medigap. Partnership HealthPlan runs Medi-Cal across the region.</p>",
         intro=["North of Sacramento the Medicare question changes shape: it is less about which of many plans and more about whether an Advantage plan exists at your address with a network you can reach. Redding and Chico have real menus built on Mercy, Shasta Regional and Enloe; the coast and the mountains have thin ones, and specialty care usually means Sacramento or the Bay Area.",
                "For a lot of North State households, Original Medicare with a Medigap policy and a Part D plan is the coverage that works everywhere &mdash; at the local hospital, at UC Davis, and at the grandchildren&rsquo;s in Oregon. We say so when it is true."],
         faqs=[("Which Medicare plans are available in Redding and Chico?", "A moderate Medicare Advantage menu in Shasta and Butte counties, thin or none in the most rural counties, every Medigap carrier in California and the full Part D lineup. For 2026 several carriers withdrew from rural North State counties."),
               ("Does Mercy Redding or Enloe take my Advantage plan?", NET),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)
def std(nm, county_menu):
    return [(f"Which Medicare plans are available in {nm}?", county_menu), (f"Will my {nm} doctors take a Medicare Advantage plan?", NET), ("How much does your help cost?", COST)]
DEEP = "typically offers a deep Medicare Advantage menu, every Medigap carrier in California, and the full Part D lineup. Availability is set by county and changes each plan year."
MOD = "typically offers a moderate Medicare Advantage menu, every Medigap carrier in California, and the full Part D lineup. Availability is set by county and changes each plan year."
CLOSE = "We compare what is sold at your ZIP code, confirm your doctors and medical group, and set Advantage beside a Medigap policy so the trade-off is plain."

CITIES = [
    city("los-angeles", "Los Angeles", "Los Angeles County", "los-angeles-county", "losangeles",
         "The largest Medicare market in America, a care map divided among Kaiser, UCLA, Cedars-Sinai, Keck USC, Providence and City of Hope &mdash; and the city where Anthem&rsquo;s PPO exit for 2026 sent the most people shopping.",
         ["Los Angeles offers dozens of Advantage plans, many Dual Special Needs and Medi-Medi Plans, every Medigap carrier in California and the full Part D lineup. Plans work through delegated medical groups, so the same plan can mean UCLA doctors in Westwood and a different group in the Valley; Cedars-Sinai, UCLA, Keck and City of Hope each contract on their own terms, and Kaiser is reached only through Senior Advantage.",
          "We compare what is sold at your ZIP code, confirm your doctors and their medical group, and check whether a Medicare Savings Program or Medi-Medi Plan applies."],
         ["Kaiser Permanente Los Angeles &amp; West LA (Senior Advantage only)", "UCLA Health", "Cedars-Sinai", "Keck Medicine of USC", "Providence (Saint John&rsquo;s, Holy Cross, Tarzana)", "City of Hope", "LA General Medical Center", "VA Greater Los Angeles"],
         "Westwood, the Westside, Hollywood, Silver Lake, the San Fernando Valley, Downtown, Koreatown, Boyle Heights, South LA, San Pedro, Northeast LA",
         [("Which Medicare plans are available in Los Angeles?", "Los Angeles County " + DEEP + " For 2026 Anthem&rsquo;s Advantage PPOs left and Aetna reduced its plans here."), ("Does UCLA or Cedars-Sinai take my Advantage plan?", NET), ("Can I keep Kaiser?", KAISER)],
         ["long-beach", "pasadena", "santa-clarita", "torrance"]),
    city("long-beach", "Long Beach", "Los Angeles County", "los-angeles-county", "harbor",
         "MemorialCare Long Beach Medical Center, Dignity St. Mary, Kaiser and the VA Long Beach anchor a city with a large veteran population and a South Bay retiree base that shops on network first.",
         ["Long Beach shares Los Angeles County&rsquo;s deep menu. MemorialCare and its medical group anchor most of the non-Kaiser Advantage plans here, St. Mary contracts separately, Kaiser runs its own system from Downey and Harbor City, and the Tibor Rubin VA serves veterans across the South Bay.", CLOSE],
         ["MemorialCare Long Beach Medical Center", "Dignity Health St. Mary", "Kaiser Permanente Downey &amp; Harbor City (Senior Advantage only)", "Lakewood Regional", "VA Long Beach (Tibor Rubin)"],
         "Belmont Shore, Bixby Knolls, Naples, Lakewood, Signal Hill, Seal Beach, Los Alamitos, Leisure World, Cerritos",
         std("Long Beach", "Los Angeles County " + DEEP), ["los-angeles", "torrance", "huntington-beach"]),
    city("pasadena", "Pasadena", "Los Angeles County", "los-angeles-county", "sierra",
         "Huntington Health, City of Hope in Duarte, Kaiser Baldwin Park and the San Gabriel Valley&rsquo;s many medical groups &mdash; a Medicare decision that often turns on a cancer-center or Cedars-affiliate question.",
         ["Pasadena and the San Gabriel Valley sit inside Los Angeles County&rsquo;s deep menu. Huntington Health (now affiliated with Cedars-Sinai) anchors the non-Kaiser plans, City of Hope in Duarte contracts selectively with Advantage plans and accepts Original Medicare, and the valley&rsquo;s medical groups decide which specialists each plan reaches.", CLOSE],
         ["Huntington Health (Cedars-Sinai)", "City of Hope (Duarte)", "Kaiser Permanente Baldwin Park (Senior Advantage only)", "Methodist Hospital of Southern California (Arcadia)", "USC Arcadia Hospital"],
         "South Pasadena, San Marino, Altadena, Arcadia, Sierra Madre, Glendale, La Ca&ntilde;ada Flintridge, Monrovia, Alhambra, San Gabriel",
         [("Which Medicare plans are available in Pasadena?", "Los Angeles County " + DEEP), ("Does City of Hope take Medicare Advantage?", "City of Hope accepts Original Medicare and therefore any Medigap policy, and contracts with some Advantage plans and not others, changing yearly. We confirm the plan&rsquo;s City of Hope status in writing before you enroll."), ("How much does your help cost?", COST)],
         ["los-angeles", "santa-clarita"]),
    city("santa-clarita", "Santa Clarita", "Los Angeles County", "los-angeles-county", "valley",
         "Henry Mayo Newhall, Facey Medical Group, Kaiser and Providence Holy Cross &mdash; a retiree-heavy valley at the county&rsquo;s north edge where the plan-versus-group question is unusually clear.",
         ["Santa Clarita shares Los Angeles County&rsquo;s menu, but the local map is simple: Henry Mayo Newhall is the hospital, Facey (Providence) and a handful of other groups are the doctors, and Kaiser serves members from its Santa Clarita medical offices with hospital care in Panorama City and Woodland Hills. Which group your doctor belongs to decides most Advantage choices here.", CLOSE],
         ["Henry Mayo Newhall Hospital", "Facey Medical Group (Providence)", "Kaiser Permanente Santa Clarita (Senior Advantage only)", "Providence Holy Cross (Mission Hills)", "UCLA Health Santa Clarita"],
         "Valencia, Newhall, Saugus, Canyon Country, Stevenson Ranch, Castaic, Acton, Agua Dulce",
         std("Santa Clarita", "Los Angeles County " + DEEP), ["los-angeles", "pasadena"]),
    city("torrance", "Torrance &amp; the South Bay", "Los Angeles County", "los-angeles-county", "coast",
         "Torrance Memorial (Cedars-Sinai), Providence Little Company of Mary, Kaiser South Bay and UCLA Harbor &mdash; and one of the largest retiree communities on the Los Angeles coast.",
         ["The South Bay shares Los Angeles County&rsquo;s deep menu, anchored locally by Torrance Memorial and its IPA, Providence Little Company of Mary in Torrance and San Pedro, and Kaiser&rsquo;s South Bay medical center in Harbor City. Palos Verdes, Redondo and Manhattan Beach retirees tend to choose on which of those systems holds their doctors.", CLOSE],
         ["Torrance Memorial Medical Center (Cedars-Sinai)", "Providence Little Company of Mary", "Kaiser Permanente South Bay (Senior Advantage only)", "Harbor-UCLA Medical Center", "VA Long Beach"],
         "Torrance, Redondo Beach, Manhattan Beach, Hermosa Beach, Palos Verdes, Rolling Hills, Lomita, Gardena, San Pedro, El Segundo",
         std("Torrance", "Los Angeles County " + DEEP), ["long-beach", "los-angeles"]),
    city("anaheim", "Anaheim", "Orange County", "orange-county", "losangeles",
         "UCI Health, Providence St. Joseph and St. Jude, Kaiser Anaheim and AHMC&rsquo;s hospitals &mdash; north Orange County&rsquo;s menu is deep, and the medical group decides the doctors.",
         ["Anaheim sits in Orange County&rsquo;s competitive Advantage market: SCAN, Alignment, Blue Shield, UnitedHealthcare, Humana, Wellcare and Kaiser all sell here, mostly at $0 premium. Each non-Kaiser plan works through a medical group (Optum, Monarch, St. Joseph Heritage, Greater Newport), and that group decides whether your UCI or St. Jude specialist is reachable.", CLOSE],
         ["UCI Health (Orange &amp; Fountain Valley)", "Providence St. Joseph (Orange) &amp; St. Jude (Fullerton)", "Kaiser Permanente Anaheim (Senior Advantage only)", "AHMC Anaheim Regional", "West Anaheim Medical Center"],
         "Anaheim Hills, Fullerton, Orange, Placentia, Yorba Linda, Brea, Garden Grove, Buena Park, Cypress",
         std("Anaheim", "Orange County " + DEEP), ["irvine", "huntington-beach", "long-beach"]),
    city("irvine", "Irvine &amp; Newport Beach", "Orange County", "orange-county", "coast",
         "Hoag, UCI Medical Center&rsquo;s new Irvine campus, MemorialCare and Kaiser Irvine &mdash; the county&rsquo;s most affluent Medicare market, where Medigap and the birthday rule get more use than almost anywhere.",
         ["Irvine and Newport Beach share Orange County&rsquo;s deep menu, but many residents here choose Original Medicare with a Medigap policy for unrestricted access to Hoag, UCI and Cedars or UCLA up the freeway. For those who prefer Advantage, Hoag&rsquo;s own medical group, Greater Newport Physicians, Optum and Monarch each define a different set of doctors.", CLOSE],
         ["Hoag Hospital (Newport Beach &amp; Irvine)", "UCI Health", "MemorialCare Orange Coast", "Kaiser Permanente Irvine (Senior Advantage only)", "Providence Mission Hospital"],
         "Newport Beach, Newport Coast, Corona del Mar, Tustin, Costa Mesa, Lake Forest, Laguna Beach, Laguna Hills, Aliso Viejo",
         std("Irvine", "Orange County " + DEEP), ["anaheim", "huntington-beach", "mission-viejo"]),
    city("huntington-beach", "Huntington Beach", "Orange County", "orange-county", "coast",
         "Hoag, MemorialCare Orange Coast, Huntington Beach Hospital and Kaiser &mdash; a coastal retiree city with a large veteran population and a lot of Medigap policies.",
         ["Huntington Beach shares Orange County&rsquo;s deep Advantage menu, anchored by Hoag and MemorialCare on the coast and Kaiser in nearby Irvine and Anaheim. A large share of residents here are veterans and military retirees, so TRICARE For Life and VA Long Beach questions come up in nearly every conversation.", CLOSE],
         ["Hoag Hospital", "MemorialCare Orange Coast &amp; Long Beach", "Huntington Beach Hospital", "Kaiser Permanente (Senior Advantage only)", "VA Long Beach"],
         "Huntington Harbour, Seal Beach, Fountain Valley, Westminster, Sunset Beach, Costa Mesa",
         std("Huntington Beach", "Orange County " + DEEP), ["irvine", "anaheim", "long-beach"]),
    city("mission-viejo", "Mission Viejo &amp; South Orange County", "Orange County", "orange-county", "sierra",
         "Providence Mission Hospital, MemorialCare Saddleback, Kaiser and the Laguna Woods retirement community &mdash; the highest concentration of Medicare beneficiaries in the county.",
         ["South County shares Orange County&rsquo;s deep menu, anchored by Providence Mission in Mission Viejo and Laguna Beach, MemorialCare Saddleback in Laguna Hills, and Kaiser&rsquo;s Irvine medical center. Laguna Woods Village alone holds thousands of Medicare households, and plan reps line up for it every October.", CLOSE],
         ["Providence Mission Hospital", "MemorialCare Saddleback", "Kaiser Permanente Irvine (Senior Advantage only)", "Hoag Irvine", "Rancho Mission Viejo medical groups"],
         "Laguna Woods, Laguna Niguel, Laguna Hills, Lake Forest, Rancho Santa Margarita, San Juan Capistrano, Dana Point, San Clemente, Ladera Ranch",
         std("Mission Viejo", "Orange County " + DEEP), ["irvine", "oceanside"]),
    city("san-diego", "San Diego", "San Diego County", "san-diego-county", "harbor",
         "Scripps, Sharp, UC San Diego Health and Kaiser &mdash; and the largest military-retiree population in the nation, which changes the Medicare math for a third of the city.",
         ["San Diego offers a deep Advantage menu, Medi-Medi Plans, every Medigap carrier in California and the full Part D lineup. The first choice is the system: Sharp and its medical groups, Scripps (selective with Advantage contracts), UC San Diego Health, or Kaiser through Senior Advantage. For TRICARE For Life households, Original Medicare plus TFL is usually the whole answer.", CLOSE],
         ["Scripps Health", "Sharp HealthCare", "UC San Diego Health", "Kaiser Permanente San Diego (Senior Advantage only)", "Naval Medical Center San Diego (TRICARE)", "VA San Diego (La Jolla)"],
         "La Jolla, Point Loma, Coronado, Clairemont, Mission Valley, North Park, Rancho Bernardo, Carmel Valley, Mira Mesa, Tierrasanta, La Mesa, El Cajon",
         [("Which Medicare plans are available in San Diego?", "San Diego County " + DEEP), ("Does Scripps take my Advantage plan?", "Scripps accepts Original Medicare and therefore any Medigap policy, and has been selective about Advantage contracts in recent years. We confirm the plan&rsquo;s Scripps status in writing before you enroll."), ("How much does your help cost?", COST)],
         ["san-diego-navy", "chula-vista", "oceanside", "escondido"]),
    city("chula-vista", "Chula Vista &amp; the South Bay", "San Diego County", "san-diego-county", "harbor",
         "Sharp Chula Vista, Scripps Mercy Chula Vista and Kaiser&rsquo;s South Bay clinics &mdash; a border community with a large dual-eligible population and its own cross-border Medicare habits.",
         ["Chula Vista shares San Diego County&rsquo;s deep menu, anchored locally by Sharp Chula Vista and Scripps Mercy. Many South Bay residents qualify for Medi-Cal alongside Medicare, and the county&rsquo;s Medi-Medi Plans matter here; so does the reminder that Medicare does not pay for care in Tijuana except in narrow circumstances.", CLOSE],
         ["Sharp Chula Vista Medical Center", "Scripps Mercy Hospital Chula Vista", "Kaiser Permanente San Diego (Senior Advantage only)", "Paradise Valley Hospital (National City)"],
         "Eastlake, Otay Ranch, Bonita, National City, Imperial Beach, San Ysidro, Spring Valley",
         std("Chula Vista", "San Diego County " + DEEP), ["san-diego", "san-diego-navy"]),
    city("oceanside", "Oceanside &amp; North County", "San Diego County", "san-diego-county", "coast",
         "Tri-City Medical Center, Scripps Encinitas, Palomar and Camp Pendleton&rsquo;s Naval Hospital &mdash; North County&rsquo;s Medicare market is deep, and its Marine-retiree community makes TRICARE For Life the first question.",
         ["Oceanside, Carlsbad, Vista and Encinitas share San Diego County&rsquo;s menu, anchored by Tri-City, Scripps Encinitas and Palomar. Camp Pendleton next door means thousands of Marine and Navy retirees with TRICARE For Life, for whom Original Medicare plus TFL usually needs no supplement. Veterans without TRICARE use the Oceanside VA clinic and VA San Diego.", CLOSE],
         ["Tri-City Medical Center", "Scripps Memorial Encinitas", "Palomar Health", "Kaiser Permanente San Marcos (Senior Advantage only)", "Naval Hospital Camp Pendleton (TRICARE)", "VA Oceanside clinic"],
         "Carlsbad, Vista, San Marcos, Encinitas, Fallbrook, Bonsall, Camp Pendleton, Solana Beach",
         std("Oceanside", "San Diego County " + DEEP), ["san-diego-navy", "escondido", "san-diego"]),
    city("escondido", "Escondido &amp; Inland North County", "San Diego County", "san-diego-county", "vineyards",
         "Palomar Medical Center, Kaiser San Marcos and Scripps and Sharp referrals &mdash; inland North County is retiree country with a moderate menu and long drives to the coast.",
         ["Escondido, Poway, Ramona and Valley Center sit inside San Diego County&rsquo;s deep menu, but the local anchors are Palomar Health and Kaiser San Marcos, with Scripps and Sharp reachable by plan contract. Ramona, Julian and the backcountry have the county&rsquo;s thinnest access, which is where Medigap&rsquo;s no-network coverage earns its premium.", CLOSE],
         ["Palomar Medical Center Escondido &amp; Poway", "Kaiser Permanente San Marcos (Senior Advantage only)", "Scripps Health", "Sharp HealthCare", "Graybill &amp; Palomar medical groups"],
         "Poway, San Marcos, Rancho Bernardo, Valley Center, Ramona, Fallbrook, Rancho Pe&ntilde;asquitos, Julian",
         std("Escondido", "San Diego County " + DEEP), ["oceanside", "san-diego", "temecula"]),
    city("riverside", "Riverside", "Riverside County", "inland-empire", "desert",
         "Riverside Community, Riverside University Health System, Kaiser Riverside and Loma Linda referrals &mdash; the Inland Empire&rsquo;s largest city and a deep, price-competitive Advantage market.",
         ["Riverside offers a deep Advantage menu built on Riverside Community Hospital (HCA), the county&rsquo;s own system, Parkview and Kaiser, with Loma Linda reachable by contract. Inland Empire Health Plan runs the region&rsquo;s Medi-Medi Plan for people with both Medicare and Medi-Cal, a large group here.", CLOSE],
         ["Riverside Community Hospital (HCA)", "Riverside University Health System", "Kaiser Permanente Riverside (Senior Advantage only)", "Parkview Community Hospital", "Loma Linda University Health", "VA Loma Linda"],
         "Canyon Crest, Woodcrest, Moreno Valley, Corona, Norco, Jurupa Valley, Eastvale, Perris, Menifee",
         std("Riverside", "Riverside County " + DEEP), ["san-bernardino", "temecula", "palm-springs"]),
    city("san-bernardino", "San Bernardino", "San Bernardino County", "inland-empire", "sierra",
         "Loma Linda University Health, Dignity St. Bernardine, Kaiser Fontana, Arrowhead Regional and the VA Loma Linda &mdash; the county seat of the largest county in the country, with a deep menu in the valley and a thin one in the mountains.",
         ["San Bernardino and the valley cities offer a deep Advantage menu anchored by Loma Linda (the region&rsquo;s academic center, selective with contracts), Kaiser Fontana and Ontario, Dignity St. Bernardine and Community, and Arrowhead Regional. Up the hill in Big Bear, Lake Arrowhead and Crestline the menu shortens sharply, and the high desert saw carrier exits for 2026.", CLOSE],
         ["Loma Linda University Health", "Kaiser Permanente Fontana &amp; Ontario (Senior Advantage only)", "Dignity Health St. Bernardine &amp; Community", "Arrowhead Regional Medical Center", "VA Loma Linda"],
         "Redlands, Highland, Loma Linda, Rialto, Fontana, Colton, Yucaipa, Rancho Cucamonga, Ontario, Lake Arrowhead, Big Bear",
         std("San Bernardino", "San Bernardino County " + DEEP), ["riverside", "victorville", "palm-springs"]),
    city("temecula", "Temecula &amp; Murrieta", "Riverside County", "inland-empire", "vineyards",
         "Temecula Valley Hospital, Loma Linda Murrieta, Southwest Healthcare and Kaiser&rsquo;s Wildomar clinics &mdash; one of the fastest-growing retirement destinations in California, with a menu that has caught up to it.",
         ["Southwest Riverside County offers a deep Advantage menu these days, anchored by Temecula Valley Hospital, Loma Linda University Medical Center Murrieta, Southwest Healthcare&rsquo;s Rancho Springs and Inland Valley hospitals, and Kaiser clinics with hospital care in Riverside. Many residents came from Orange County and San Diego with doctors they want to keep, which is a network question we answer before anything else.", CLOSE],
         ["Temecula Valley Hospital", "Loma Linda University Medical Center Murrieta", "Southwest Healthcare (Rancho Springs, Inland Valley)", "Kaiser Permanente Wildomar clinics (Senior Advantage only)", "Scripps &amp; Sharp (San Diego referrals)"],
         "Murrieta, Menifee, Wildomar, Lake Elsinore, Canyon Lake, Hemet, San Jacinto, Fallbrook, De Luz",
         std("Temecula", "Riverside County " + DEEP), ["riverside", "escondido", "oceanside"]),
    city("palm-springs", "Palm Springs &amp; the Coachella Valley", "Riverside County", "inland-empire", "desert",
         "Eisenhower Health, Desert Regional, JFK Memorial and a seasonal population that leaves every June &mdash; the desert&rsquo;s Medicare question is whether the plan travels.",
         ["The Coachella Valley shares Riverside County&rsquo;s menu, but the local map is small: Eisenhower Health in Rancho Mirage (selective with Advantage contracts), Tenet&rsquo;s Desert Regional and JFK Memorial, and clinics from the big Southern California systems. A large share of residents split the year with the Pacific Northwest, Canada or the coast, and for them a Medigap policy&rsquo;s nationwide access is often the deciding factor. Our sister site in Arizona serves the same snowbird circuit on the other side of the river.", CLOSE],
         ["Eisenhower Health (Rancho Mirage)", "Desert Regional Medical Center (Palm Springs)", "JFK Memorial Hospital (Indio)", "Desert Oasis &amp; Eisenhower medical groups", "Loma Linda (referrals)"],
         "Rancho Mirage, Palm Desert, Cathedral City, La Quinta, Indian Wells, Indio, Desert Hot Springs, Coachella, Sun City Palm Desert",
         [("Which Medicare plans are available in Palm Springs?", "Riverside County " + DEEP + " Eisenhower Health contracts selectively; we confirm before you enroll."), ("Does my plan work when I leave for the summer?", "A Medigap policy with Original Medicare works anywhere in the country that takes Medicare. Most Advantage plans cover only emergencies outside their service area, though some PPOs carry travel benefits. We look at both addresses before recommending anything."), ("How much does your help cost?", COST)],
         ["riverside", "san-bernardino", "temecula"]),
    city("victorville", "Victorville &amp; the High Desert", "San Bernardino County", "inland-empire", "desert",
         "Victor Valley Global, Desert Valley, St. Mary Apple Valley and long drives to Loma Linda &mdash; the high desert is where the 2026 Advantage pullback showed up in San Bernardino County.",
         ["Victorville, Hesperia, Apple Valley and Barstow have a shorter Advantage menu than the valley below, and UnitedHealthcare and Humana&rsquo;s 2026 county exits thinned it further in places. The local hospitals are Victor Valley Global, Desert Valley and Providence St. Mary in Apple Valley; specialty care means Loma Linda or Kaiser Fontana down the Cajon Pass. Original Medicare with a Medigap policy is a common choice here for that reason.", CLOSE],
         ["Victor Valley Global Medical Center", "Desert Valley Hospital", "Providence St. Mary Medical Center (Apple Valley)", "Barstow Community Hospital", "Loma Linda University Health (referrals)"],
         "Hesperia, Apple Valley, Adelanto, Oak Hills, Phelan, Barstow, Lucerne Valley, Spring Valley Lake",
         std("Victorville", "San Bernardino County " + MOD), ["san-bernardino", "riverside"]),
    city("san-francisco", "San Francisco", "San Francisco County", "bay-area", "goldengate",
         "UCSF, Sutter CPMC, Kaiser San Francisco, Dignity and Chinese Hospital &mdash; the highest Medigap premiums in California and a city where the Kaiser-or-not decision comes before anything else.",
         ["San Francisco offers Kaiser Senior Advantage plus a moderate non-Kaiser Advantage menu built on Sutter CPMC, Dignity, Chinese Hospital and UCSF contracts (UCSF is selective), every Medigap carrier in California and the full Part D lineup. Medigap premiums here run among the highest in the state, so the annual birthday-rule re-shop is worth real money.", CLOSE],
         ["UCSF Health", "Sutter Health CPMC", "Kaiser Permanente San Francisco (Senior Advantage only)", "Dignity Health St. Francis &amp; St. Mary&rsquo;s", "Chinese Hospital", "VA San Francisco"],
         "the Sunset, the Richmond, Noe Valley, the Marina, Pacific Heights, Bernal Heights, the Mission, Excelsior, Daly City, South San Francisco",
         [("Which Medicare plans are available in San Francisco?", "San Francisco " + MOD), ("Does UCSF take my Advantage plan?", NET), ("Can I keep Kaiser?", KAISER)],
         ["oakland", "san-jose", "walnut-creek"]),
    city("oakland", "Oakland &amp; the East Bay", "Alameda County", "bay-area", "goldengate",
         "Kaiser&rsquo;s headquarters city, Sutter Alta Bates Summit, UCSF Benioff Oakland and Alameda Health System &mdash; the East Bay is Kaiser country, with a real alternative for people who want out.",
         ["Oakland, Berkeley, Alameda and the inner East Bay offer Kaiser Senior Advantage (the largest Medicare plan here by far), a moderate non-Kaiser Advantage menu built on Sutter Alta Bates Summit and Alameda Health System, every Medigap carrier in California and the full Part D lineup. Alameda Alliance and the county&rsquo;s Medi-Medi Plans serve dual-eligible residents.", CLOSE],
         ["Kaiser Permanente Oakland &amp; Richmond (Senior Advantage only)", "Sutter Alta Bates Summit", "UCSF Benioff Children&rsquo;s / UCSF referrals", "Alameda Health System (Highland)", "Stanford Health Care Tri-Valley (Pleasanton)"],
         "Berkeley, Alameda, Piedmont, Emeryville, San Leandro, Hayward, Castro Valley, Richmond, El Cerrito, Pleasanton, Dublin, Livermore",
         [("Which Medicare plans are available in Oakland?", "Alameda County " + MOD), ("Does Alta Bates Summit take my Advantage plan?", NET), ("Can I keep Kaiser?", KAISER)],
         ["san-francisco", "walnut-creek", "san-jose"]),
    city("san-jose", "San Jose &amp; Silicon Valley", "Santa Clara County", "bay-area", "sierra",
         "Stanford, Kaiser Santa Clara and San Jose, Sutter&rsquo;s Palo Alto Medical Foundation, El Camino and Good Samaritan &mdash; a county where the Stanford question decides a lot of Medicare choices.",
         ["Santa Clara County offers Kaiser Senior Advantage, a moderate non-Kaiser Advantage menu built on Sutter/PAMF, El Camino, Good Samaritan (HCA) and Santa Clara Valley Medical Center, with Stanford contracting selectively, every Medigap carrier in California and the full Part D lineup. Santa Clara Family Health Plan runs the county&rsquo;s Medi-Medi Plan.", CLOSE],
         ["Stanford Health Care", "Kaiser Permanente Santa Clara &amp; San Jose (Senior Advantage only)", "Sutter Health / Palo Alto Medical Foundation", "El Camino Health", "Good Samaritan Hospital (HCA)", "Santa Clara Valley Medical Center", "VA Palo Alto"],
         "Willow Glen, Almaden, Cambrian, Evergreen, Santa Clara, Sunnyvale, Cupertino, Campbell, Los Gatos, Saratoga, Palo Alto, Mountain View, Milpitas, Morgan Hill, Gilroy",
         [("Which Medicare plans are available in San Jose?", "Santa Clara County " + MOD), ("Does Stanford take my Advantage plan?", "Stanford Health Care accepts Original Medicare and therefore any Medigap policy, and contracts with some Advantage plans and not others, changing yearly. We confirm the plan&rsquo;s Stanford status in writing before you enroll."), ("How much does your help cost?", COST)],
         ["san-francisco", "oakland"]),
    city("walnut-creek", "Walnut Creek &amp; Contra Costa", "Contra Costa County", "bay-area", "vineyards",
         "John Muir Health, Kaiser Walnut Creek and Antioch, Sutter Delta and Rossmoor&rsquo;s thousands of Medicare households &mdash; Contra Costa is a two-system county and shops that way.",
         ["Contra Costa County offers Kaiser Senior Advantage, a moderate non-Kaiser menu built mainly on John Muir Health and its medical group, plus Sutter Delta in the east county, every Medigap carrier in California and the full Part D lineup. Rossmoor in Walnut Creek is one of the largest retirement communities in Northern California and every carrier knows it.", CLOSE],
         ["John Muir Health (Walnut Creek &amp; Concord)", "Kaiser Permanente Walnut Creek &amp; Antioch (Senior Advantage only)", "Sutter Delta (Antioch)", "Contra Costa Regional Medical Center", "Stanford &amp; UCSF (referrals)"],
         "Rossmoor, Lafayette, Orinda, Moraga, Danville, San Ramon, Alamo, Concord, Pleasant Hill, Martinez, Brentwood, Antioch",
         [("Which Medicare plans are available in Walnut Creek?", "Contra Costa County " + MOD), ("Does John Muir take my Advantage plan?", NET), ("Can I keep Kaiser?", KAISER)],
         ["oakland", "san-francisco"]),
    city("santa-rosa", "Santa Rosa &amp; the North Bay", "Sonoma County", "bay-area", "redwoods",
         "Sutter Santa Rosa, Providence Santa Rosa Memorial, Kaiser Santa Rosa and Petaluma Valley &mdash; wine country&rsquo;s Medicare menu is shorter than the city&rsquo;s, and wildfire SEPs are not theoretical here.",
         ["Sonoma, Marin and Napa counties offer Kaiser Senior Advantage, a shorter non-Kaiser Advantage menu built on Sutter, Providence, MarinHealth and Queen of the Valley, every Medigap carrier in California and the full Part D lineup. The North Bay has lived through several FEMA-declared fires; our wildfire page explains the Special Enrollment Period and prescription rules that follow one.", CLOSE],
         ["Sutter Santa Rosa Regional", "Providence Santa Rosa Memorial", "Kaiser Permanente Santa Rosa &amp; San Rafael (Senior Advantage only)", "MarinHealth Medical Center", "Providence Queen of the Valley (Napa)", "Adventist Health St. Helena"],
         "Petaluma, Rohnert Park, Sebastopol, Healdsburg, Windsor, Sonoma, Novato, San Rafael, Mill Valley, Napa, St. Helena",
         std("Santa Rosa", "Sonoma County " + MOD), ["san-francisco", "walnut-creek"]),
    city("sacramento", "Sacramento", "Sacramento County", "sacramento-valley", "vineyards",
         "UC Davis Health, Sutter, Dignity Mercy and Kaiser, the state&rsquo;s largest CalPERS retiree population and the VA at Mather &mdash; a four-system Medicare market where each plan draws its own line.",
         ["Sacramento offers a moderate-to-deep Advantage menu built on Sutter, Dignity and (selectively) UC Davis, Kaiser Senior Advantage from three medical centers, every Medigap carrier in California and the full Part D lineup. CalPERS retirees choose from CalPERS&rsquo;s own Medicare plans instead, which we explain plainly because the two menus get confused constantly.", CLOSE],
         ["UC Davis Health", "Sutter Medical Center Sacramento", "Dignity Health Mercy General &amp; Mercy San Juan", "Kaiser Permanente Sacramento &amp; South Sacramento (Senior Advantage only)", "VA Northern California (Mather)"],
         "East Sacramento, Land Park, Carmichael, Fair Oaks, Citrus Heights, Rancho Cordova, Arden-Arcade, Natomas, Orangevale, Davis, West Sacramento",
         [("Which Medicare plans are available in Sacramento?", "Sacramento County " + DEEP), ("Does UC Davis take my Advantage plan?", NET), ("I am retiring through CalPERS. Does this site&rsquo;s advice apply to me?", "Partly. CalPERS retirees must enroll in Medicare Part B and choose from CalPERS&rsquo;s own Medicare plans, which are separate from the individual-market plans we sell. We can still help you understand Medicare itself, Part B timing, IRMAA and how the CalPERS options compare in plain English.")],
         ["roseville", "elk-grove", "folsom"]),
    city("roseville", "Roseville &amp; Placer County", "Placer County", "sacramento-valley", "sierra",
         "Sutter Roseville, Kaiser Roseville and the Sun City Roseville and Lincoln Hills retirement communities &mdash; one of the fastest-growing Medicare populations in Northern California, with the foothills right behind it.",
         ["Roseville, Rocklin, Lincoln and Auburn offer a moderate Advantage menu built on Sutter Roseville and Kaiser Roseville, with UC Davis reachable by contract, every Medigap carrier in California and the full Part D lineup. Higher up in Placer, Nevada and El Dorado counties, menus shorten and several carriers left rural counties for 2026.", CLOSE],
         ["Sutter Roseville Medical Center", "Kaiser Permanente Roseville (Senior Advantage only)", "Adventist Health &amp; Rideout", "Sutter Auburn Faith", "UC Davis Health (referrals)"],
         "Rocklin, Lincoln, Sun City Roseville, Sun City Lincoln Hills, Granite Bay, Loomis, Auburn, Grass Valley, Nevada City",
         std("Roseville", "Placer County " + MOD), ["sacramento", "folsom"]),
    city("elk-grove", "Elk Grove", "Sacramento County", "sacramento-valley", "valley",
         "Kaiser South Sacramento, Dignity Methodist, Sutter and UC Davis referrals &mdash; south Sacramento County&rsquo;s largest city shares the capital&rsquo;s deep menu.",
         ["Elk Grove sits inside Sacramento County&rsquo;s menu, anchored locally by Kaiser South Sacramento and Dignity Health Methodist Hospital, with Sutter and UC Davis a short drive north. A large and diverse Medicare population here includes many dual-eligible households, served by the county&rsquo;s Medi-Medi Plans.", CLOSE],
         ["Kaiser Permanente South Sacramento (Senior Advantage only)", "Dignity Health Methodist Hospital", "Sutter Medical Center Sacramento", "UC Davis Health"],
         "Laguna, Sheldon, Wilton, Galt, Rancho Murieta, South Sacramento, Florin, Vineyard",
         std("Elk Grove", "Sacramento County " + DEEP), ["sacramento", "folsom"]),
    city("folsom", "Folsom &amp; El Dorado Hills", "Sacramento County", "sacramento-valley", "sierra",
         "Mercy Hospital of Folsom, Kaiser and Sutter clinics, Marshall Medical in Placerville and the foothills beyond &mdash; where Sacramento&rsquo;s menu meets El Dorado County&rsquo;s shorter one.",
         ["Folsom shares Sacramento County&rsquo;s deep menu; El Dorado Hills, Cameron Park and Placerville are in El Dorado County, where the menu is shorter and built on Marshall Medical Center and Sacramento referrals. The county line runs through a lot of neighborhoods here, and it changes which plans are sold.", CLOSE],
         ["Dignity Health Mercy Hospital of Folsom", "Kaiser Permanente Folsom &amp; Roseville (Senior Advantage only)", "Sutter Roseville", "Marshall Medical Center (Placerville)", "UC Davis Health"],
         "El Dorado Hills, Cameron Park, Shingle Springs, Placerville, Granite Bay, Orangevale, Rancho Cordova, Fair Oaks",
         std("Folsom", "Sacramento County " + DEEP), ["sacramento", "roseville"]),
    city("fresno", "Fresno", "Fresno County", "central-valley", "valley",
         "Community Regional, Saint Agnes, Kaiser Fresno and the VA Central California &mdash; the Valley&rsquo;s medical hub, with a deep menu and a large dual-eligible population.",
         ["Fresno offers a deep Advantage menu built on Community Health System, Saint Agnes and their medical groups, Kaiser Senior Advantage, Medi-Medi Plans (CalViva and Health Net in the county), every Medigap carrier in California and the full Part D lineup. Many households here qualify for a Medicare Savings Program, so we check that first.", CLOSE],
         ["Community Regional Medical Center &amp; Clovis Community", "Saint Agnes Medical Center", "Kaiser Permanente Fresno (Senior Advantage only)", "Fresno Heart &amp; Surgical", "VA Central California"],
         "Clovis, Fig Garden, Sunnyside, Sanger, Reedley, Selma, Kingsburg, Madera",
         std("Fresno", "Fresno County " + DEEP), ["visalia", "lemoore-nas", "bakersfield"]),
    city("bakersfield", "Bakersfield", "Kern County", "central-valley", "desert",
         "Adventist Health Bakersfield, Dignity Memorial and Mercy, Kern Medical and a deep, price-competitive menu &mdash; Kern County shops on medical group, and Edwards Air Force Base retirees shop on TRICARE.",
         ["Bakersfield offers a deep Advantage menu built on Adventist Health, Dignity Health Memorial and Mercy, and Kern Medical, with Kaiser present through clinics and contracted hospitals, Medi-Medi Plans for dual-eligible residents, every Medigap carrier in California and the full Part D lineup. The Kern County menu thins quickly in the mountains and the desert toward Ridgecrest.", CLOSE],
         ["Adventist Health Bakersfield", "Dignity Health Memorial Hospital &amp; Mercy", "Kern Medical", "Kaiser Permanente Kern County (Senior Advantage only)", "Bakersfield Heart Hospital"],
         "Seven Oaks, Rosedale, Oildale, Delano, Shafter, Wasco, Tehachapi, Arvin, Taft, Ridgecrest",
         std("Bakersfield", "Kern County " + DEEP), ["fresno", "visalia"]),
    city("modesto", "Modesto", "Stanislaus County", "central-valley", "valley",
         "Doctors Medical Center, Sutter Memorial Medical Center and Kaiser Modesto &mdash; a three-system county with a deep menu and a lot of retirees who came from the Bay Area for the price of a house.",
         ["Modesto offers a deep Advantage menu built on Tenet&rsquo;s Doctors Medical Center, Sutter&rsquo;s Memorial Medical Center and Kaiser Modesto, Medi-Medi Plans for dual-eligible residents, every Medigap carrier in California and the full Part D lineup. Many Stanislaus County retirees keep Bay Area or Stanford specialists, which is a plan-contract question we settle first.", CLOSE],
         ["Doctors Medical Center (Tenet)", "Sutter Memorial Medical Center", "Kaiser Permanente Modesto (Senior Advantage only)", "Stanislaus Surgical Hospital", "Stanford &amp; UCSF (referrals)"],
         "Turlock, Ceres, Oakdale, Riverbank, Salida, Patterson, Ripon, Manteca",
         std("Modesto", "Stanislaus County " + DEEP), ["stockton", "fresno"]),
    city("stockton", "Stockton", "San Joaquin County", "central-valley", "valley",
         "Dignity St. Joseph&rsquo;s, Adventist Health Dameron, San Joaquin General and Kaiser Manteca &mdash; a deep menu and one of the Valley&rsquo;s largest dual-eligible populations.",
         ["Stockton and Lodi offer a deep Advantage menu built on St. Joseph&rsquo;s, Dameron and Lodi Memorial, Kaiser Senior Advantage from Manteca and Modesto, Health Plan of San Joaquin&rsquo;s Medi-Medi Plan for dual-eligible residents, every Medigap carrier in California and the full Part D lineup.", CLOSE],
         ["Dignity Health St. Joseph&rsquo;s Medical Center", "Adventist Health Dameron &amp; Lodi Memorial", "San Joaquin General Hospital", "Kaiser Permanente Manteca &amp; Stockton clinics (Senior Advantage only)", "Sutter Tracy"],
         "Lodi, Manteca, Tracy, Lathrop, Lincoln Village, Brookside, Morada, Woodbridge",
         std("Stockton", "San Joaquin County " + DEEP), ["modesto", "elk-grove"]),
    city("visalia", "Visalia &amp; Tulare County", "Tulare County", "central-valley", "valley",
         "Kaweah Health, Adventist Health Tulare and Hanford, Sierra View and long drives to Fresno &mdash; the south Valley has a moderate menu and the state&rsquo;s highest share of dual-eligible seniors.",
         ["Visalia, Tulare, Porterville and Hanford offer a moderate Advantage menu built on Kaweah Health, Adventist Health and Sierra View, Medi-Medi Plans for the large dual-eligible population, every Medigap carrier in California and the full Part D lineup. Specialty care often means Fresno, and we check the referral path before the premium.", CLOSE],
         ["Kaweah Health (Visalia)", "Adventist Health Tulare &amp; Hanford", "Sierra View Medical Center (Porterville)", "Community Health System (Fresno referrals)", "VA Central California (Fresno)"],
         "Tulare, Porterville, Hanford, Lemoore, Exeter, Dinuba, Lindsay, Three Rivers",
         std("Visalia", "Tulare County " + MOD), ["fresno", "lemoore-nas", "bakersfield"]),
    city("santa-barbara", "Santa Barbara", "Santa Barbara County", "central-coast", "coast",
         "Cottage Health, Sansum Clinic and Marian Regional up in Santa Maria &mdash; a one-system city with a short Advantage menu, high Medigap premiums and a birthday rule that earns its keep.",
         ["Santa Barbara offers a moderate Advantage menu built on Cottage Health and Sansum Clinic (now part of Sutter), every Medigap carrier in California and the full Part D lineup. Many residents choose Original Medicare with a Medigap policy for unrestricted access to Cottage plus UCLA or Cedars for specialty care, and re-shop the premium each year under the birthday rule.", CLOSE],
         ["Cottage Health (Santa Barbara, Goleta Valley, Santa Ynez)", "Sansum Clinic (Sutter)", "Dignity Health Marian Regional (Santa Maria)", "Lompoc Valley Medical Center", "UCLA &amp; Cedars-Sinai (referrals)"],
         "Goleta, Montecito, Carpinteria, Santa Ynez, Solvang, Lompoc, Santa Maria, Orcutt, Isla Vista",
         std("Santa Barbara", "Santa Barbara County " + MOD), ["ventura", "vandenberg-sfb", "san-luis-obispo"]),
    city("ventura", "Ventura &amp; Oxnard", "Ventura County", "central-coast", "coast",
         "Community Memorial, Dignity St. John&rsquo;s, Ventura County Medical Center and Kaiser clinics without a Kaiser hospital &mdash; a county that borders Los Angeles and shops a very different menu.",
         ["Ventura County offers a moderate Advantage menu built on Community Memorial Health System, Dignity Health St. John&rsquo;s, the county system and Los Robles in Thousand Oaks, Kaiser Senior Advantage through Kaiser&rsquo;s Ventura County clinics with hospital care at Woodland Hills, Gold Coast Health Plan&rsquo;s Medi-Medi Plan, every Medigap carrier in California and the full Part D lineup.", CLOSE],
         ["Community Memorial Health System (Ventura &amp; Ojai)", "Dignity Health St. John&rsquo;s (Oxnard &amp; Camarillo)", "Ventura County Medical Center", "Los Robles Health System (Thousand Oaks)", "Kaiser Permanente Ventura County clinics (Senior Advantage only)"],
         "Oxnard, Camarillo, Ojai, Port Hueneme, Thousand Oaks, Simi Valley, Moorpark, Santa Paula, Fillmore",
         std("Ventura", "Ventura County " + MOD), ["santa-barbara", "los-angeles", "santa-clarita"]),
    city("san-luis-obispo", "San Luis Obispo", "San Luis Obispo County", "central-coast", "coast",
         "Tenet&rsquo;s Sierra Vista and Twin Cities, Dignity French Hospital and Arroyo Grande &mdash; a two-system county with a short Advantage menu and a lot of Medigap policies.",
         ["San Luis Obispo County offers a moderate Advantage menu built on Tenet and Dignity Health hospitals and their medical groups, every Medigap carrier in California and the full Part D lineup. With only two systems and long drives to Stanford or UCLA for specialty care, Original Medicare with a Medigap policy is the most common choice among our clients here.", CLOSE],
         ["Tenet Health Central Coast (Sierra Vista, Twin Cities)", "Dignity Health French Hospital &amp; Arroyo Grande Community", "Dignity Health Marian Regional (Santa Maria)", "Stanford &amp; UCLA (referrals)"],
         "Pismo Beach, Arroyo Grande, Grover Beach, Morro Bay, Los Osos, Atascadero, Paso Robles, Templeton, Cambria, Nipomo",
         std("San Luis Obispo", "San Luis Obispo County " + MOD), ["santa-barbara", "vandenberg-sfb", "monterey"]),
    city("monterey", "Monterey &amp; Salinas", "Monterey County", "central-coast", "coast",
         "Montage Health on the Peninsula, Salinas Valley Health, Natividad and the Naval Postgraduate School&rsquo;s retiree community &mdash; a county where the Advantage menu is short and the hospital you want is usually obvious.",
         ["Monterey County offers a moderate Advantage menu built on Montage Health&rsquo;s Community Hospital of the Monterey Peninsula, Salinas Valley Health and Natividad, every Medigap carrier in California and the full Part D lineup. The Peninsula has a large military-retiree population from the Naval Postgraduate School, the Defense Language Institute and the former Fort Ord, so TRICARE For Life questions are constant.", CLOSE],
         ["Montage Health / Community Hospital of the Monterey Peninsula", "Salinas Valley Health", "Natividad Medical Center", "Dominican Hospital (Santa Cruz, Dignity)", "Stanford Health Care (referrals)"],
         "Carmel, Pacific Grove, Pebble Beach, Seaside, Marina, Salinas, Hollister, Watsonville, Santa Cruz, Aptos",
         std("Monterey", "Monterey County " + MOD), ["san-luis-obispo", "san-jose"]),
    city("redding", "Redding", "Shasta County", "north-state", "redwoods",
         "Mercy Medical Center Redding, Shasta Regional and referrals to UC Davis &mdash; the North State&rsquo;s medical hub, and the region where carriers pulled out of rural counties for 2026.",
         ["Redding offers a moderate Advantage menu built on Dignity Health Mercy Redding and Shasta Regional Medical Center, every Medigap carrier in California and the full Part D lineup. The counties around it (Trinity, Siskiyou, Modoc, Lassen) have thin menus or none after the 2026 exits, and for many households up here Original Medicare with a Medigap policy is the coverage that works at Mercy, at UC Davis and on the road.", CLOSE],
         ["Dignity Health Mercy Medical Center Redding", "Shasta Regional Medical Center", "Mayers Memorial (Fall River Mills)", "UC Davis Health (referrals)", "VA Redding clinic"],
         "Anderson, Shasta Lake, Palo Cedro, Cottonwood, Red Bluff, Burney, Weaverville, Yreka, Mount Shasta",
         [("Which Medicare plans are available in Redding?", "Shasta County " + MOD + " Surrounding rural counties have fewer plans, and several carriers withdrew for 2026."), ("Does Mercy Redding take my Advantage plan?", NET), ("How much does your help cost?", COST)],
         ["chico", "eureka"]),
    city("chico", "Chico", "Butte County", "north-state", "valley",
         "Enloe Health, Oroville Hospital and a county rebuilt after the Camp Fire &mdash; Chico&rsquo;s Medicare menu is moderate, and the wildfire rules are lived experience here.",
         ["Chico, Paradise and Oroville offer a moderate Advantage menu built on Enloe Health and Oroville Hospital, every Medigap carrier in California and the full Part D lineup. Butte County knows the disaster Special Enrollment Period and the Part D early-refill rule better than any county in the state; our wildfire page explains both.", CLOSE],
         ["Enloe Health (Chico)", "Oroville Hospital", "Adventist Health Feather River clinics (Paradise)", "Sutter (Yuba City)", "UC Davis Health (referrals)"],
         "Paradise, Oroville, Magalia, Durham, Gridley, Willows, Orland, Yuba City, Marysville",
         std("Chico", "Butte County " + MOD), ["redding", "roseville"]),
    city("eureka", "Eureka &amp; the North Coast", "Humboldt County", "north-state", "redwoods",
         "Providence St. Joseph Eureka, Mad River Community and Adventist Health in Mendocino County &mdash; the North Coast is the thinnest Medicare market in California, and the honest answer here is often Medigap.",
         ["Humboldt, Del Norte and Mendocino counties have short Advantage menus (thinner after the 2026 exits), every Medigap carrier in California and the full Part D lineup. Providence St. Joseph in Eureka is the region&rsquo;s hospital, specialty care means the Bay Area or Redding, and Partnership HealthPlan handles Medi-Cal. Original Medicare with a Medigap policy is what most of our North Coast clients end up choosing, and we say so.", CLOSE],
         ["Providence St. Joseph Hospital (Eureka)", "Mad River Community Hospital (Arcata)", "Sutter Coast Hospital (Crescent City)", "Adventist Health (Ukiah, Fort Bragg, Willits)", "UCSF &amp; UC Davis (referrals)"],
         "Arcata, McKinleyville, Fortuna, Ferndale, Trinidad, Crescent City, Ukiah, Fort Bragg, Mendocino",
         std("Eureka", "Humboldt County " + MOD.replace("moderate", "short")), ["redding", "santa-rosa"]),
]

BASES = [
    dict(slug="san-diego-navy", name="Naval Base San Diego, Miramar &amp; Camp Pendleton", region="san-diego-county", scene="harbor",
         title="Medicare Near Naval Base San Diego, Miramar &amp; Camp Pendleton | ECOS Medicare Solutions",
         desc="Medicare for Navy and Marine retirees and veterans around San Diego: TRICARE For Life, Naval Medical Center San Diego, Naval Hospital Camp Pendleton, the VA in La Jolla, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Naval Base San Diego, MCAS Miramar and Camp Pendleton",
         sub="San Diego County retires more sailors and Marines than anywhere in the country. TRICARE For Life, Balboa, Camp Pendleton&rsquo;s hospital, the La Jolla VA &mdash; and a Medicare decision that looks different from a civilian one, explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Navy or Marine family in San Diego",
         intro=["San Diego County holds the largest military-retiree population in the nation, and most reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having, and whether its network includes Scripps, Sharp or UC San Diego.",
                "Veterans without TRICARE use the VA San Diego Healthcare System in La Jolla and its clinics from Oceanside to Chula Vista, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. Naval Medical Center San Diego and Naval Hospital Camp Pendleton see retirees on a space-available basis; neither is a substitute for Medicare."],
         systems=["Naval Medical Center San Diego (Balboa, TRICARE)", "Naval Hospital Camp Pendleton (TRICARE)", "VA San Diego Healthcare System (La Jolla)", "Scripps Health", "Sharp HealthCare", "UC San Diego Health", "Tri-City Medical Center"],
         communities="Coronado, Point Loma, Tierrasanta, Chula Vista, Clairemont, Mira Mesa, Oceanside, Vista, Fallbrook, Carlsbad, Murrieta",
         faqs=[("I retired from the Navy with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you."),
               ("I use the La Jolla VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using Balboa or the Camp Pendleton hospital after 65?", "Retirees can be seen on a space-available basis under TRICARE rules; Medicare does not pay there. Most San Diego retirees pair TFL with civilian care at Scripps, Sharp or UC San Diego.")],
         nearby=["san-diego", "oceanside", "chula-vista"], cta="Retired from the Navy or the Marines? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="travis-afb", name="Travis Air Force Base", region="bay-area", scene="vineyards",
         title="Medicare Near Travis Air Force Base, Fairfield | ECOS Medicare Solutions",
         desc="Medicare for Air Force retirees and veterans around Travis AFB, Fairfield and Vacaville: TRICARE For Life, David Grant Medical Center, the VA in Martinez and Mather, and which Solano County plans fit. From a retired Air Force officer.",
         h1="Medicare near Travis Air Force Base",
         sub="Solano County has one of the largest Air Force retiree communities in the West. TRICARE For Life, David Grant Medical Center, NorthBay and Kaiser Vacaville, the VA in Martinez and Mather &mdash; and a Medicare decision that looks different from a civilian one, explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Travis family",
         intro=["Fairfield, Vacaville and Suisun hold thousands of Air Force retirees, and most reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having, and whether its network includes NorthBay, Sutter Solano or Kaiser.",
                "Veterans without TRICARE use the VA Northern California system, with the Martinez outpatient clinic, the Mather medical center in Sacramento and the Fairfield clinic near the base, and here the Part B timing question is the one that matters. David Grant Medical Center on base sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["David Grant USAF Medical Center (TRICARE)", "VA Northern California (Martinez, Mather, Fairfield clinic)", "NorthBay Health", "Kaiser Permanente Vacaville &amp; Vallejo (Senior Advantage only)", "Sutter Solano Medical Center", "UC Davis Health"],
         communities="Fairfield, Suisun City, Vacaville, Rio Vista, Dixon, Vallejo, Benicia, Green Valley, Cordelia",
         faqs=[("I retired from the Air Force with TRICARE For Life. Which Medicare plan should I pick?", "For most TFL families, Original Medicare Parts A and B with TFL is complete coverage. An MA-only Advantage plan can add dental, vision and hearing without duplicating your pharmacy benefit; we check whether one is worth it for you."),
               ("Does Medicare pay at David Grant?", "No. David Grant sees retirees on a space-available basis under TRICARE rules. Most Travis retirees pair TFL with civilian care at NorthBay, Sutter Solano or Kaiser."),
               ("I use the VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["walnut-creek", "santa-rosa", "sacramento"], cta="Retired from Travis? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="vandenberg-sfb", name="Vandenberg Space Force Base", region="central-coast", scene="coast",
         title="Medicare Near Vandenberg Space Force Base, Lompoc | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans around Vandenberg SFB, Lompoc and Santa Maria: TRICARE For Life, the Vandenberg clinic, Marian Regional and Lompoc Valley, the Santa Maria VA clinic, and which Central Coast plans fit.",
         h1="Medicare near Vandenberg Space Force Base",
         sub="Lompoc and Santa Maria hold a large Air Force and Space Force retiree community on a stretch of coast with a short Medicare menu. TRICARE For Life, the base clinic, Marian Regional, Lompoc Valley and the Santa Maria VA clinic &mdash; explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Vandenberg family",
         intro=["Northern Santa Barbara County&rsquo;s retirees mostly reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left is whether a thin local Advantage menu offers an MA-only plan worth having, and whether its network includes Marian Regional and Lompoc Valley.",
                "Veterans without TRICARE use the Santa Maria VA clinic and the VA Greater Los Angeles system for hospital care, and here the Part B timing question is the one that matters: VA care is not creditable for Part B. The Vandenberg clinic sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["Vandenberg SFB medical clinic (TRICARE)", "Santa Maria VA clinic; VA Greater Los Angeles", "Dignity Health Marian Regional Medical Center", "Lompoc Valley Medical Center", "Cottage Health (Santa Barbara)", "Sansum Clinic"],
         communities="Lompoc, Vandenberg Village, Santa Maria, Orcutt, Buellton, Solvang, Guadalupe, Nipomo, Arroyo Grande",
         faqs=[("I retired with TRICARE For Life near Vandenberg. Do I need anything besides Medicare?", "Usually not. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. We check whether an MA-only Advantage plan sold in Santa Barbara County adds enough dental, vision or hearing to be worth it."),
               ("Does Medicare pay at the base clinic?", "No. The Vandenberg clinic sees retirees on a space-available basis under TRICARE rules. Most retirees here pair TFL with civilian care at Marian Regional or Lompoc Valley."),
               ("I use the VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["santa-barbara", "san-luis-obispo"], cta="Retired from Vandenberg? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="lemoore-nas", name="NAS Lemoore &amp; Edwards Air Force Base", region="central-valley", scene="desert",
         title="Medicare Near NAS Lemoore &amp; Edwards AFB | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans around Naval Air Station Lemoore, Edwards Air Force Base and China Lake: TRICARE For Life, the base clinics, Adventist Health, Antelope Valley Medical Center, the Fresno and Loma Linda VA, and which plans fit.",
         h1="Medicare near NAS Lemoore, Edwards AFB and China Lake",
         sub="The Valley and the high desert hold Navy and Air Force retirees a long way from a big hospital. TRICARE For Life, the base clinics, Adventist Health Hanford, Antelope Valley and Ridgecrest Regional, the Fresno and Loma Linda VA &mdash; explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Lemoore, Edwards or China Lake family",
         intro=["Hanford, Lemoore, Lancaster, Palmdale and Ridgecrest hold thousands of retirees who reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left is whether a local Advantage plan&rsquo;s network reaches the specialists you need in Fresno, Bakersfield or Los Angeles, which is the real question in these towns.",
                "Veterans without TRICARE use VA Central California in Fresno, the VA Loma Linda system and its Lancaster and Ridgecrest clinics, and here the Part B timing question is the one that matters: VA care is not creditable for Part B. The Lemoore and Edwards clinics see retirees on a space-available basis; they are not a substitute for Medicare."],
         systems=["Naval Health Clinic Lemoore &amp; Edwards 412th Medical Group (TRICARE)", "VA Central California (Fresno); VA Loma Linda (Lancaster, Ridgecrest clinics)", "Adventist Health Hanford &amp; Selma", "Antelope Valley Medical Center (Lancaster)", "Palmdale Regional", "Ridgecrest Regional Hospital", "Kaweah Health (Visalia)"],
         communities="Hanford, Lemoore, Visalia, Lancaster, Palmdale, Rosamond, Tehachapi, Ridgecrest, California City, Boron",
         faqs=[("I retired with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one sold in your county is worth it."),
               ("Does Medicare pay at the Lemoore or Edwards clinic?", "No. The base clinics see retirees on a space-available basis under TRICARE rules. Most retirees here pair TFL with civilian care at Adventist Health, Antelope Valley or Ridgecrest Regional."),
               ("I use the Fresno VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["visalia", "fresno", "bakersfield"], cta="Retired from Lemoore, Edwards or China Lake? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
